services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api_produits

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  produit-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: produit-container
    restart: always
    ports:
      - 8081:8082

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/api_produits
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      - postgres
